### ISSUE TITLE
[Bug] Sign in with Github on Render deploy redirects to localhost:3000

### ISSUE THREAD

**Issue by abhinavsharma** [Bartek532/rssmarkable#44]
**To Reproduce**
- No existing account.
- go to https://rssmarkable.onrender.com/
- sign in
- use github

**Actual behavior**
- notice that redirect is to localhost:3000

**Expected behavior**
- redirect should have been to onrender.com

**Comment by Bartek532** [comment]
Thanks for reporting!

Probably I forgot to set one env variable.

Anyway I'm thinking about migrating from Render, so I will take it into an account :)

**Comment by Bartek532** [comment]
Fixed during migration to Fly.io.
